import fs from 'node:fs';
import { PATHS } from './paths.js';

const HEADER_KEY = '//';
const HEADER = [
  'Permanent name -> codepoint map. This file is the icon set\'s contract with',
  'every app that has already shipped: a name keeps its codepoint forever, a',
  'freed codepoint is never handed to a different icon, and nothing is ever',
  'renumbered. Deleting an icon moves its entry to "retired" so the codepoint',
  'stays burned. Generated by `npm run build`; commit it with your icon.',
];

const toHex = (n) => n.toString(16).padStart(4, '0');
const fromHex = (s) => parseInt(s, 16);

const sortByName = (entries) =>
  Object.fromEntries(entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));

export function readCodepoints() {
  if (!fs.existsSync(PATHS.codepoints)) return { icons: {}, retired: {} };
  const raw = JSON.parse(fs.readFileSync(PATHS.codepoints, 'utf8'));
  return { icons: raw.icons ?? {}, retired: raw.retired ?? {} };
}

/**
 * Resolve the codepoint for every current icon.
 *
 * - a name already in the map keeps its codepoint, always
 * - a name in `retired` that reappears gets its *own* old codepoint back
 * - anything new takes the next unused codepoint above the high-water mark, so
 *   codepoints are never reused even after a deletion
 * - a name that no longer exists on disk is retired, not deleted
 *
 * @returns {{ assignments: Map<string, number>, next: object, changes: string[] }}
 */
export function assignCodepoints(iconNames, range) {
  const current = readCodepoints();
  const start = fromHex(range.start);
  const end = fromHex(range.end);

  const icons = {};
  const retired = { ...current.retired };
  const changes = [];

  const used = new Set(
    [...Object.values(current.icons), ...Object.values(retired)].map(fromHex),
  );
  let highWater = used.size ? Math.max(...used) : start - 1;

  const names = [...iconNames].sort();
  for (const name of names) {
    if (current.icons[name]) {
      icons[name] = current.icons[name];
      continue;
    }
    if (retired[name]) {
      icons[name] = retired[name];
      delete retired[name];
      changes.push(`restored "${name}" to its original U+${icons[name].toUpperCase()}`);
      continue;
    }
    const next = highWater + 1;
    if (next > end) {
      throw new Error(
        `codepoint range U+${range.start}..U+${range.end} is exhausted; widen "codepoints" in icons.config.json`,
      );
    }
    highWater = next;
    used.add(next);
    icons[name] = toHex(next);
    changes.push(`assigned "${name}" the new codepoint U+${toHex(next).toUpperCase()}`);
  }

  const present = new Set(names);
  for (const [name, code] of Object.entries(current.icons)) {
    if (present.has(name)) continue;
    retired[name] = code;
    changes.push(`retired "${name}" (U+${code.toUpperCase()}); its codepoint stays reserved`);
  }

  const next = {
    [HEADER_KEY]: HEADER,
    range: { start: range.start, end: range.end },
    icons: sortByName(Object.entries(icons)),
    retired: sortByName(Object.entries(retired)),
  };

  const assignments = new Map(Object.entries(icons).map(([name, code]) => [name, fromHex(code)]));
  return { assignments, next, changes };
}

export function writeCodepoints(next) {
  const serialised = `${JSON.stringify(next, null, 2)}\n`;
  const existing = fs.existsSync(PATHS.codepoints) ? fs.readFileSync(PATHS.codepoints, 'utf8') : null;
  if (existing === serialised) return false;
  fs.writeFileSync(PATHS.codepoints, serialised);
  return true;
}
