#!/usr/bin/env node
/**
 * Serves the gallery on your own network, so you can open it on a phone
 * without the page ever leaving your firewall.
 *
 *   npm run serve                 http://<your-lan-ip>:4173
 *   npm run serve -- --port 8080
 *   npm run serve -- --token hunter2    require ?t=hunter2 once, then a cookie
 *   npm run serve -- --host 127.0.0.1   this machine only
 *
 * No dependencies, no build step, no outbound calls. It serves the generated
 * gallery plus the font files, and nothing else.
 */
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { REPO_ROOT, PATHS } from './lib/paths.js';

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.ttf': 'font/ttf',
  '.woff2': 'font/woff2',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.txt': 'text/plain; charset=utf-8',
};

/** Mount points, in order. The server exposes these and nothing above them. */
const MOUNTS = [
  { prefix: '/fonts', dir: PATHS.fontsOut },
  { prefix: '/svg', dir: PATHS.svg },
  { prefix: '', dir: PATHS.preview },
];

function parseArgs(argv) {
  const args = { port: 4173, host: '0.0.0.0', token: process.env.ICONS_TOKEN || '' };
  for (let i = 0; i < argv.length; i++) {
    const [flag, inline] = argv[i].split('=');
    const value = inline ?? argv[i + 1];
    const take = () => { if (inline === undefined) i++; return value; };
    if (flag === '--port' || flag === '-p') args.port = Number(take());
    else if (flag === '--host') args.host = take();
    else if (flag === '--token' || flag === '-t') args.token = take();
    else if (flag === '--help' || flag === '-h') args.help = true;
  }
  return args;
}

/** Every IPv4 address this machine answers on, so you know what to type. */
function lanAddresses() {
  return Object.values(os.networkInterfaces()).flat()
    .filter((n) => n && n.family === 'IPv4' && !n.internal)
    .map((n) => n.address);
}

/**
 * Resolve a URL path to a file inside one of the mounts.
 * Returns null for anything that escapes, so `..` cannot walk the disk.
 */
function resolve(urlPath) {
  let decoded;
  try {
    decoded = decodeURIComponent(urlPath.split('?')[0]);
  } catch {
    return null;
  }
  if (decoded.endsWith('/')) decoded += 'index.html';
  if (decoded === '') decoded = '/index.html';

  for (const mount of MOUNTS) {
    if (mount.prefix && !decoded.startsWith(`${mount.prefix}/`)) continue;
    const relative = mount.prefix ? decoded.slice(mount.prefix.length) : decoded;
    const full = path.resolve(mount.dir, `.${relative}`);
    const root = path.resolve(mount.dir);
    if (full !== root && !full.startsWith(root + path.sep)) continue;
    if (fs.existsSync(full) && fs.statSync(full).isFile()) return full;
  }
  return null;
}

const timingSafeEqual = (a, b) => {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  return ab.length === bb.length && crypto.timingSafeEqual(ab, bb);
};

function authorised(req, token) {
  if (!token) return true;
  const url = new URL(req.url, 'http://localhost');
  const query = url.searchParams.get('t');
  if (query && timingSafeEqual(query, token)) return 'set-cookie';
  const cookie = (req.headers.cookie || '')
    .split(';').map((c) => c.trim()).find((c) => c.startsWith('icons_token='));
  if (cookie && timingSafeEqual(decodeURIComponent(cookie.slice('icons_token='.length)), token)) return true;
  return false;
}

export function serve(args) {
  const { port, host, token } = args;

  const server = http.createServer((req, res) => {
    if (req.method !== 'GET' && req.method !== 'HEAD') {
      res.writeHead(405, { allow: 'GET, HEAD' }).end('Method not allowed');
      return;
    }

    const auth = authorised(req, token);
    if (!auth) {
      res.writeHead(401, { 'content-type': 'text/plain; charset=utf-8' })
        .end('Add ?t=<token> to the URL.\n');
      return;
    }

    const file = resolve(req.url);
    if (!file) {
      res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' }).end('Not found\n');
      return;
    }

    const headers = {
      'content-type': MIME[path.extname(file).toLowerCase()] || 'application/octet-stream',
      'content-length': fs.statSync(file).size,
      // The gallery is regenerated by `npm run build`; never serve a stale copy.
      'cache-control': 'no-cache',
      // This is a local tool, not a website: keep it out of any embed.
      'x-content-type-options': 'nosniff',
      'referrer-policy': 'no-referrer',
    };
    if (auth === 'set-cookie') {
      headers['set-cookie'] = `icons_token=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax`;
    }

    res.writeHead(200, headers);
    if (req.method === 'HEAD') return res.end();
    fs.createReadStream(file).pipe(res);
  });

  server.on('error', (error) => {
    if (error.code === 'EADDRINUSE') {
      console.error(`port ${port} is already in use - try: npm run serve -- --port ${port + 1}`);
      process.exit(1);
    }
    throw error;
  });

  server.listen(port, host, () => {
    const suffix = token ? `/?t=${encodeURIComponent(token)}` : '/';
    console.log(`\n  ${path.relative(process.cwd(), PATHS.preview) || 'preview'}/ is being served\n`);
    console.log(`  this machine   http://localhost:${port}${suffix}`);
    if (host === '0.0.0.0') {
      const addresses = lanAddresses();
      if (addresses.length === 0) {
        console.log('  on your network  (no external network interface found)');
      } else {
        for (const address of addresses) {
          console.log(`  on your network  http://${address}:${port}${suffix}`);
        }
        console.log('\n  Open a network address on your phone - same wifi, never leaves it.');
      }
    } else {
      console.log(`  bound to ${host} only`);
    }
    if (token) console.log('\n  Token required. The link above sets a cookie on first load.');
    console.log('\n  Ctrl+C to stop.\n');
  });

  return server;
}

const isMain = process.argv[1] && import.meta.url === `file://${path.resolve(process.argv[1])}`;
if (isMain) {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(`usage: npm run serve -- [--port 4173] [--host 0.0.0.0] [--token SECRET]

  --port   port to listen on (default 4173)
  --host   interface to bind (default 0.0.0.0, all interfaces)
  --token  require ?t=SECRET on first request; also reads ICONS_TOKEN`);
    process.exit(0);
  }
  if (!fs.existsSync(path.join(PATHS.preview, 'index.html'))) {
    console.error('preview/index.html is missing - run `npm run build` first');
    process.exit(1);
  }
  serve(args);
}

export { parseArgs, resolve, REPO_ROOT };
